### ISSUE TITLE
[Feature] On what bases you set verified and security properties ?

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#2175]
**In the below example :-** 

```
{
  "_id": "62e8a3d28edb7c3c91a5584a",
  "name": "Tether",
  "symbol": "USDT",
  "address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
  "decimals": 6,
  "logoURI": "https://common.onekey-asset.com/token/evm-1/0xdAC17F958D2ee523a2206206994597C13D831ec7.jpg",
  "impl": "evm",
  "status": "LISTED",
  "verified": true,
  "security": false,
  "addToIndex": true,
  "chainId": "1",
  "source": [
    "sushi",
    "Uniswap Labs Default",
    "Coingecko"
  ],
  "checked": true,
  "coingeckoId": "tether",
  "swftId": "USDT(ERC20)",
  "createdAt": "2022-08-02T04:10:58.205Z",
  "updatedAt": "2022-11-28T15:13:18.247Z",
  "__v": 0,
  "marketCap": 67600751622.405464
}
```

You can see 2 properties which is **verified** and **security**. How and on what base, do you set them ?

**Comment by qwang1113** [comment]
Hey @Mustafa-Agha, due to some reasons, we use verified and security flags to indicate whether a token is trustworthy:

- verified === true means that the token appears in two collection lists and does not have entries considered dangerous in the contract, indicating relative trustworthiness

- security === true means that the token may have some security-related entries, and users need to be particularly careful when trading and using it

- When both are true, security takes precedence.
