### ISSUE TITLE
[BUG]: APK in github releases is not universal (only for arm64-v8a arch)

### ISSUE THREAD

**Issue by emanuelb** [OneKeyHQ/app-monorepo#2868]
**Describe the bug**

The apk downloaded from github releases such as in : https://github.com/OneKeyHQ/app-monorepo/releases 
the file https://github.com/OneKeyHQ/app-monorepo/releases/download/v4.3.0/OneKey-Wallet-4.3.0-android.apk

will have only ./lib/arm64-v8a directory in it, therefore it wont be installed on devices of different arch (such as x86/x86_64/armeabi/armeabi-v7a/mips/mips64)

related is errors in https://twitter.com/BitcoinWalletz/status/1648259324228288513/photo/2

Fix:

publish universal apk in github release or website downloads so the apk will be installed on all supported devices.

for details about universal apk:
universal apk generation https://developer.android.com/build/configure-apk-splits#configure-abi-split
universal apk generation from app bundle: `--mode=universal` https://developer.android.com/tools/bundletool#generate_apks

**Comment by sunnylqm** [comment]
Thank you for bringing this to our attention. We would like to clarify that our decision to limit testing to only the most popular architectures and platforms is intentional. Due to limited resources, it is simply not feasible for us to test on every possible combination. However we will definitely revisit this in the future if the need arises and we have more resources at our disposal.
