### ISSUE TITLE
[Feature] Add app to F-droid repo.

### ISSUE THREAD

**Issue by lazycaat** [OneKeyHQ/app-monorepo#3605]
**Is your feature request related to a problem? Please describe.**
Some people don't use Google Play to download programs.

**Describe the solution you'd like**
I suggest adding this app to the [F-droid](https://f-droid.org/) repo.

**Describe alternatives you've considered**
1. People can use [Obtainium](https://github.com/ImranR98/Obtainium) to update the app directly from.
2. You can create your own repository for F-droid.

**Additional context**
Adding an app to the f-droid repository will not only allow those who don't want to or can't use Google Play to download the app, but it will also increase the reputation of the app due to the fact that apps in f-droid are screened.

**Comment by rayston92** [comment]
will do, thx for the heads up.

**Comment by rayston92** [comment]
@PatrickChoo 

We should add F-Droid to our download channels and incorporate a direct link on our official website.

**Comment by ghost** [comment]
Does OneKey agree to have its app included in the F-droid repo and "store"? https://gitlab.com/fdroid/rfp/-/issues/2274

**Comment by licaon-kter** [comment]
So which license is it under? Readme says Apache2

but there's this elephant here: https://github.com/OneKeyHQ/app-monorepo/blob/onekey/LICENSE.md
> "Reference use" means use of the software within your company as a reference, in read only form, for the sole purposes of debugging your products, maintaining your products, or enhancing the interoperability of your products with the software, and specifically excludes the right to distribute the software outside of your company.

...that wants to limit redistribution? Umm, this would invalidate Apache 2, right?

**Comment by rayston92** [comment]
@PatrickChoo  we should deploy app on F-droid.

**Comment by PatrickChoo** [comment]
@lazycaat Thank you for your suggestion and thanks to @licaon-kter from F-Droid for the assistance. 🙏

Regarding the inclusion policy of F-Droid, there are several modifications that OneKey would need to make in order to be listed on F-Droid:

• It cannot rely on Google Play services.
• It cannot use proprietary tracking or analytics services such as Google Analytics, Firebase Crashlytics, or Mixpanel. Only FLOSS services like ACRA can be used.
• F-Droid will review copyright licenses and only accept those compatible with DFSG, FSF, GNU, and OSI (referencing SPDX). Currently, the project’s license is not purely Apache 2, and we would need to discuss whether to change the license terms.
• In-app updates are not allowed, and updates can only be handled via the F-Droid update mechanism, requiring separate management.

Given these requirements, we have decided not to consider adding OneKey to F-Droid at this time.
